### PR TITLE
Update to latest flutter.

### PR DESCRIPTION
**Pull request by apwilson**
You piqued my interest.  I took a couple hours this morning and here's Armadillo running at the lastest flutter rev.  One main problem that's remaining is the need to provide TextStyles to the MaterialApp or the various Text widgets.

Feel free to take or leave this patch, it can be used as a reference of the minimum set of things that'd need to change to make armadillo work.

I tested this with an Android Studio tablet simulator.  Haven't tried with simulated Android phone.

### CODE REVIEW

**Comment by apwilson** [comment]
Also, there were some gradle issues so I just did a flutter create then replaced the contents of the android and ios directory with the resulting output - that may have resulted in the loss of icons and/or any package strings in those directories.

**Comment by logo4poop** [comment]
Are you on the discord? https://discord.gg/5TW5Cpe

**Comment by nobody5050** [comment]
wow, you are awesome!
but seriously: wow dude.

**Comment by nmcain** [comment]
Wow!

**Comment by nmcain** [comment]
Legacy code is a pain to work with, and you edited 144 files! Amazing!

**Comment by nmcain** [comment]
Let's merge this.

**Comment by apwilson** [comment]
Please double check your main use cases still work!  I didn't do as much
testing of this cl as I would normally.  What I did test seemed okay.

**Comment by EnderNightLord-ChromeBook** [comment]
Hey there! I'm impressed with your work. I'm the creator and I want to invite you to the dahlia team: https://discord.gg/5TW5Cpe

**Comment by nmcain** [comment]
I have forked the original, to retain the old code, but I am now merging the pull request.

**Comment by apwilson** [comment]
cool, glad to help

**Comment by EnderNightLord-ChromeBook** [comment]
Yes thanks a heap!

**Pull request merged**
